# PHP
# Test and package your PHP project.
# Add steps that run tests, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/php

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  phpVersion: 7.2

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: |
    composer self-update
    composer install --no-interaction --no-progress
  displayName: 'composer install'


- script: cp .env.testing .env
  displayName: 'Laravel: ENV configuration'

- script: |
    php artisan key:generate
    php artisan config:clear
    php artisan migrate:refresh
    php artisan db:seed --env="testing"
  displayName: 'Laravel: Generate an application key, Re-cache, migrate'

- script: vendor/bin/phpmd app/ text phpmd.xml
  displayName: 'Using the PHP Code Mess Detection'

- script: vendor/bin/phpcbf --standard=psr2 app/
  displayName: 'Using the PHP Code Beautifier and Fixer'

- script: vendor/bin/phpcs
  displayName: 'Using the PHP Code Sniffer'

- script: vendor/bin/phpunit --colors --debug
  displayName: 'Running PHPUnit test'